version: '2'

services: 
  consul:
    image: consul:1.15.1
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net
networks:
  sky-net:
    driver: bridge
