apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-k8s-server
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: simple-k8s-server
  template:
    metadata:
      # labels to select/identify the deployment
      labels:
        io.kompose.service: simple-k8s-server
    spec:
      containers:
      - name: simple-k8s-server
        image: "vkraken/simple-k8s-server:1.0.0"
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        
        # check that simple-k8s-server is alive and healthy
        readinessProbe:
          httpGet:
            path: /info
            port: 9090
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /info
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 5