version: '2'

services: 
  consul:
    image: consul:1.15.1
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net

  simple-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: simple-server:1.0.1
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    # more secure
    #  - PORT=8080
    #ports:
    #  - "8080:8080"
    depends_on:
      - consul
    networks:
      - sky-net
  
  simple-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: simple-client:1.0.1
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
      - simple-server
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge